WebAppAspNetFundamentals2/Controllers/CitiesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppAspNetFundamentals2.Models;
using WebAppAspNetFundamentals2.Models.Data;
using WebAppAspNetFundamentals2.Models.Service;
using WebAppAspNetFundamentals2.Models.ViewModel;

namespace WebAppAspNetFundamentals2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CitiesController : Controller
    {
        private readonly ICityService _cityService;
        private readonly ICountryService _countryService;
        private readonly IPeopleRepo _peopleRepo;

        public CitiesController(ICityService cityService, ICountryService countryService, IPeopleRepo peopleRepo)
        {
            this._cityService = cityService;
            _countryService = countryService;
            _peopleRepo = peopleRepo;
        }

        // GET: CitiesController
        public ActionResult Index()
        {
            var model = _cityService.All();
            return View(model);

            //return View(_cityService.JsonAll());
        }


        [HttpGet]
        public IActionResult Create()
        {
            CreateCity newcity = new CreateCity();
            newcity.CountryList = _countryService.All();

            return View(newcity);
        }

        [HttpPost]
        public IActionResult Create(CreateCity createCity)
        {
            if (ModelState.IsValid)
            {
                _cityService.Add(createCity);

                return RedirectToAction(nameof(Index));
            }

            return View(createCity);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            City person = _cityService.FindById(id);

            if (person == null)
            {
                return RedirectToAction(nameof(Index));
            }

            _cityService.Remove(id);
            return RedirectToAction(nameof(Index));
        }
      
    }
}

WebAppAspNetFundamentals2/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppAspNetFundamentals2.Models.Data;
using WebAppAspNetFundamentals2.Models.Service;
using WebAppAspNetFundamentals2.Models.ViewModel;

namespace WebAppAspNetFundamentals2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountriesController : Controller
    {
        private readonly ICountryService _countryService;

        public CountriesController(ICountryService countryService)
        {
            _countryService = countryService;
        }

        // GET: CitiesController
        public IActionResult Index()
        {
            return View(_countryService.All());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateCountry createCountry)
        {
            if (ModelState.IsValid)
            {
                _countryService.Add(createCountry);

                return RedirectToAction(nameof(Index));
            }

            return View(createCountry);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Country person = _countryService.FindById(id);

            if (person == null)
            {
                return RedirectToAction(nameof(Index));
            }

            _countryService.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebAppAspNetFundamentals2/Controllers/LanguagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppAspNetFundamentals2.Models.Service;
using WebAppAspNetFundamentals2.Models.ViewModel;

namespace WebAppAspNetFundamentals2.Controllers
{
    [Authorize]
    public class LanguagesController : Controller
    {
        private readonly ILanguageService _languageService;

        public LanguagesController(ILanguageService languageService)
        {
            _languageService = languageService;
        }


        // GET: LanguagesController
        public ActionResult Index()
        {
            return View(_languageService.All());
        }

        // GET: LanguagesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LanguagesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LanguagesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateLanguage createLanguage)
        {
            if (ModelState.IsValid)
            {
                _languageService.Add(createLanguage);

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(createLanguage);
            }
        }

        // GET: LanguagesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LanguagesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LanguagesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LanguagesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebAppAspNetFundamentals2/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppAspNetFundamentals2.Models.ViewModel;
using WebAppAspNetFundamentals2.Models.Service;
using WebAppAspNetFundamentals2.Models.Data;
using WebAppAspNetFundamentals2.Models.Repo;
using PersonLanguage = WebAppAspNetFundamentals2.Models.Data.PersonLanguage;
using Microsoft.AspNetCore.Authorization;

namespace WebAppAspNetFundamentals2.Controllers
{
    [Authorize]
    public class PeopleController : Controller
    {
        IPeopleService _peopleService;
        private readonly IPersonLanguageRepo _personLanguangeRepo;
        private readonly ILanguageService _languageService;

        public PeopleController(IPeopleService peopleService, IPersonLanguageRepo personLanguangeRepo,
            ILanguageService languageService)
        {
            _peopleService = peopleService;
            _personLanguangeRepo = personLanguangeRepo;
            _languageService = languageService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_peopleService.All());
        }

        [HttpPost]
        public IActionResult Index(PeopleViewModel vm)
        {
            vm = _peopleService.FindBy(vm);

            return View(vm);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new CreatePersonViewModel());
        }

        [HttpPost]
        public IActionResult Create(CreatePersonViewModel createPerson)
        {
            if (ModelState.IsValid)
            {
                _peopleService.Add(createPerson);

                return RedirectToAction(nameof(Index));
            }

            return View(createPerson);
        }

        [HttpGet]
        public IActionResult ManagePersonLanguage(int id)
        {
            Person person = _peopleService.FindBy(id);

            if (person == null)
            {
                return RedirectToAction("Index");
            }

            PersonLanguagesViewModel vm = new PersonLanguagesViewModel();
            vm.Person = person;
            vm.Languages = _languageService.All();


            return View(vm);
        }

        [HttpGet]
        public IActionResult AddLanguageToPerson(int personId, int languageId)
        {
            Person person = _peopleService.FindBy(personId);

            if (person == null)
            {
                return RedirectToAction("Index");
            }



            PersonLanguage personLanguage = _personLanguangeRepo.Create
                (new PersonLanguage() { PersonId = personId, LanguageId = languageId });



            return RedirectToAction("ManagePersonLanguage", new { id = personId });
        }

        [HttpGet]
        public IActionResult RemoveLanguageToPerson(int personId, int languageId)
        {
            Person person = _peopleService.FindBy(personId);

            if (person == null)
            {
                return RedirectToAction("Index");
            }



            _personLanguangeRepo.Delete(personId, languageId);



            return RedirectToAction("ManagePersonLanguage", new { id = personId });
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Person person = _peopleService.FindBy(id);

            if (person == null)
            {
                return RedirectToAction(nameof(Index));
            }

            _peopleService.Remove(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult EditPerson(int id)
        {
            Person person = _peopleService.FindBy(id);

            if (person == null)
            {
                return RedirectToAction("Index");
            }

            EditPerson editPerson = new EditPerson();
            editPerson.Id = id;
            editPerson.CreatePerson = _peopleService.PersonToCreatePerson(person);

            return View(editPerson);
        }

        [HttpPost]
        public IActionResult EditPerson(int id, CreatePersonViewModel createPerson)
        {
            if (ModelState.IsValid)
            {
                Person car = _peopleService.EditPerson(id, createPerson);

                return RedirectToAction(nameof(Index));
            }

            EditPerson editPerson = new EditPerson();
            editPerson.Id = id;
            editPerson.CreatePerson = createPerson;

            return View(editPerson);



            //[HttpPost]
            //public IActionResult Delete(int id, DeletePerson deletePerson)
            //{
            //    Person person = _peopleService.FindBy(id);

            //    if (person == null)
            //    {
            //        return RedirectToAction("Index");
            //    }

            //    DeletePerson deletePerson = new DeletePerson();
            //    deletePerson.Delete = _peopleService.Remove(id);

            //    return View(deletePerson);
            //}
        }
    }
}
//public bool Remove(int id)
//{
//    Person originalPerson = FindBy(id);

//    if (originalPerson == null)
//    {
//        return false;
//    }
//    return _peopleRepo.Delete(originalPerson);

WebAppAspNetFundamentals2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppAspNetFundamentals2</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppAspNetFundamentals2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Index">City List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Country List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Languages" asp-action="Index">Languages List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AjaxPeople" asp-action="AjaxIndex">Ajax Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebAppAspNetFundamentals2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebAppAspNetFundamentals2/Views/Shared/_PeoplePatialView.cshtml
@model List<Person>

<div id="PeopleTable" class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-3"><h4>Name</h4></div>
            <div class="col-3"><h4>Phone Number</h4></div>
            <div class="col-3"><h4>City Id</h4></div>
            @*<div class="col-2"><h4>Country Name</h4></div>*@
            <div class="col-3"><h4>Action</h4></div>
        </div>
    </div>
</div>
<div>
    @foreach (var item in Model)
    {
        if (item == null)
        {
            <p class="col-12">List is empty</p>
        }

        <partial name="_PersonPatialView" model="item" />

    }
</div>

WebAppAspNetFundamentals2/Views/Shared/_PersonPatialView.cshtml
@model Person

<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-3"><p>@Model.Name</p></div>
            <div class="col-3"><p>@Model.PhoneNumber</p></div>
            <div class="col-3"><p>@Model.CityId</p></div>
            @*<div class="col-2"><p>@Model.CountryName</p></div>*@
            <div class="col-3">
                <a asp-action="Delete" asp-controller="People"
                   asp-route-id="@Model.Id">Delete</a>  |
                <a asp-action="ManagePersonLanguage" asp-controller="People"
                   asp-route-id="@Model.Id">Manage Person Language</a> |
                <a asp-action="EditPerson" asp-controller="People"
                   asp-route-id="@Model.Id">Edit Person</a>
            </div>
        </div>
    </div>
</div>